---
chat-format: '{WORLD_NAME}:[{PREFIX}]<{DISPLAY_NAME}> {MESSAGE}'
// chat-format: '{WORLD_NAME}({LEVEL}):[{PREFIX}]<{DISPLAY_NAME}> {MESSAGE}'
enable-formatter: true
color: ยง7 // For the next release!
disablechat: false
default-player-prefix: Default
...
Kill counter activity: false
...
death counter activity: false
...
Xp Level activity: true
...



